package br.com.sisfie.entidade;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;
import org.hibernate.validator.constraints.Email;

import br.com.arquitetura.entidade.Entidade;

/**
 * Candidato generated by hbm2java
 */
@Entity
@Table(name = "candidato", catalog = "SISFIE")
@Audited
public class Candidato extends Entidade<Integer> {

	private static final long serialVersionUID = -8268994832509721962L;

	@Id
	@Column(name = "id_candidato", unique = true, nullable = false)
	@SequenceGenerator(name = "candidato_seq", sequenceName = "candidato_id_candidato_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "candidato_seq")
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio_endereco", nullable = false)
	private Municipio municipioEndereco;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_orgao_divisao", nullable = false)
	private Orgao orgao;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_municipio_orgao", nullable = false)
	private Municipio municipioOrgao;

	@Column(name = "nome", nullable = false)
	private String nome;

	@Column(name = "flg_necessidade_especial", nullable = false)
	private Boolean necessidadeEspecial;

	@Column(name = "nom_emergencia", nullable = false)
	private String nomeEmergencia;

	@Column(name = "tel_Emergencia", nullable = false)
	private String telEmergencia;

	@Column(name = "desc_necessidade")
	private String DescricaoNecessidadeEspecial;

	@Transient
	private String necessidadeEspecialFormat;
	@Column(name = "cpf", length = 14)
	private String cpf;

	@Column(name = "logradouro")
	private String logradouro;

	@Column(name = "complemento")
	private String complemento;

	@Column(name = "tel_comercial")
	private String telComercial;

	@Column(name = "tel_celular")
	private String telCelular;

	@Column(name = "tel_residencial")
	private String telResidencial;

	@Email(message = "Email inválido")
	@Column(name = "email_pessoal")
	private String emailPessoal;

	@Email(message = "Email inválido")
	@Column(name = "email_institucional")
	private String emailInstitucional;

	@Column(name = "senha")
	private String senha;

	@Column(name = "cep")
	private String cep;

	@Column(name = "matricula", length = 50)
	private String matricula;

	@Column(name = "matricula_chefe", length = 50)
	private String matriculaChefe;

	@Column(name = "flg_nacionalidade_brasil")
	private Boolean nacionalidadeBrasil;

	@Column(name = "doc_estrangeiro", length = 255)
	private String docEstrangeiro;

	@Column(name = "FLG_ATIVO", nullable = false)
	private Boolean flgAtivo;

	@OneToMany(mappedBy = "candidato", fetch = FetchType.LAZY)
	private Set<AtuacaoCandidato> atuacaoCandidatos = new HashSet<AtuacaoCandidato>(
			0);

	@OneToMany(mappedBy = "candidato", fetch = FetchType.LAZY)
	private Set<CandidatoCargo> candidatoCargo = new HashSet<CandidatoCargo>(0);

	@OneToMany(mappedBy = "candidato", fetch = FetchType.LAZY)
	private Set<InscricaoCurso> inscricoes = new HashSet<InscricaoCurso>(0);

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_nascimento")
	private Date dataNascimento;

	@Column(name = "FLG_PRIMEIRO_ACESSO")
	private Boolean flgPrimeiroAcesso;

	@Column(name = "EMAIL_CHEFE")
	private String emailChefe;

	@Transient
	private String login;

	@Transient
	private String confirmacaoSenha;

	public Candidato() {
	}

	public Candidato(Integer id) {
		this.id = id;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Municipio getMunicipioEndereco() {
		return this.municipioEndereco;
	}

	public void setMunicipioEndereco(Municipio municipioEndereco) {
		this.municipioEndereco = municipioEndereco;
	}

	public Orgao getOrgao() {
		return this.orgao;
	}

	public void setOrgao(Orgao orgao) {
		this.orgao = orgao;
	}

	public Municipio getMunicipioOrgao() {
		return this.municipioOrgao;
	}

	public void setMunicipioOrgao(Municipio municipioOrgao) {
		this.municipioOrgao = municipioOrgao;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getLogradouro() {
		return this.logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getTelComercial() {
		return this.telComercial;
	}

	public void setTelComercial(String telComercial) {
		this.telComercial = telComercial;
	}

	public String getTelCelular() {
		return this.telCelular;
	}

	public void setTelCelular(String telCelular) {
		this.telCelular = telCelular;
	}

	public String getTelResidencial() {
		return this.telResidencial;
	}

	public void setTelResidencial(String telResidencial) {
		this.telResidencial = telResidencial;
	}

	public String getEmailPessoal() {
		return this.emailPessoal;
	}

	public void setEmailPessoal(String emailPessoal) {
		this.emailPessoal = emailPessoal;
	}

	public String getEmailInstitucional() {
		return this.emailInstitucional;
	}

	public void setEmailInstitucional(String emailInstitucional) {
		this.emailInstitucional = emailInstitucional;
	}

	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}

	public String getCep() {
		return this.cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public String getMatriculaChefe() {
		return this.matriculaChefe;
	}

	public void setMatriculaChefe(String matriculaChefe) {
		this.matriculaChefe = matriculaChefe;
	}

	public Boolean getNacionalidadeBrasil() {
		return nacionalidadeBrasil;
	}

	public void setNacionalidadeBrasil(Boolean nacionalidadeBrasil) {
		this.nacionalidadeBrasil = nacionalidadeBrasil;
	}

	public String getDocEstrangeiro() {
		return docEstrangeiro;
	}

	public void setDocEstrangeiro(String docEstrangeiro) {
		this.docEstrangeiro = docEstrangeiro;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getConfirmacaoSenha() {
		return confirmacaoSenha;
	}

	public void setConfirmacaoSenha(String confirmacaoSenha) {
		this.confirmacaoSenha = confirmacaoSenha;
	}

	public Boolean getFlgAtivo() {
		return flgAtivo;
	}

	public void setFlgAtivo(Boolean flgAtivo) {
		this.flgAtivo = flgAtivo;
	}

	public Set<AtuacaoCandidato> getAtuacaoCandidatos() {
		return atuacaoCandidatos;
	}

	public void setAtuacaoCandidatos(Set<AtuacaoCandidato> atuacaoCandidatos) {
		this.atuacaoCandidatos = atuacaoCandidatos;
	}

	public Set<CandidatoCargo> getCandidatoCargo() {
		return candidatoCargo;
	}

	public void setCandidatoCargo(Set<CandidatoCargo> candidatoCargo) {
		this.candidatoCargo = candidatoCargo;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public Boolean getFlgPrimeiroAcesso() {
		return flgPrimeiroAcesso;
	}

	public void setFlgPrimeiroAcesso(Boolean flgPrimeiroAcesso) {
		this.flgPrimeiroAcesso = flgPrimeiroAcesso;
	}

	public String getEmailChefe() {
		return emailChefe;
	}

	public void setEmailChefe(String emailChefe) {
		this.emailChefe = emailChefe;
	}

	public Set<InscricaoCurso> getInscricoes() {
		return inscricoes;
	}

	public void setInscricoes(Set<InscricaoCurso> inscricoes) {
		this.inscricoes = inscricoes;
	}

	public Boolean getNecessidadeEspecial() {
		return necessidadeEspecial;
	}

	public void setNecessidadeEspecial(Boolean necessidadeEspecial) {
		this.necessidadeEspecial = necessidadeEspecial;
	}

	public String getNomeEmergencia() {
		return nomeEmergencia;
	}

	public void setNomeEmergencia(String nomeEmergencia) {
		this.nomeEmergencia = nomeEmergencia;
	}

	public String getTelEmergencia() {
		return telEmergencia;
	}

	public void setTelEmergencia(String telEmergencia) {
		this.telEmergencia = telEmergencia;
	}

	public String getNecessidadeEspecialFormat() {
		necessidadeEspecialFormat = "Não";
		if (necessidadeEspecial != null && necessidadeEspecial) {
			necessidadeEspecialFormat = "Sim";

		}

		return necessidadeEspecialFormat;
	}

	public void setNecessidadeEspecialFormat(String necessidadeEspecialFormat) {
		this.necessidadeEspecialFormat = necessidadeEspecialFormat;
	}

	public String getDescricaoNecessidadeEspecial() {
		return DescricaoNecessidadeEspecial;
	}

	public void setDescricaoNecessidadeEspecial(
			String descricaoNecessidadeEspecial) {
		DescricaoNecessidadeEspecial = descricaoNecessidadeEspecial;
	}

}